// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGpbgq6Rt6qJO4rNfBKqxRKPQ-FmbX6RA',
    appId: '1:344217680049:web:544d69219cbe20613d0a90',
    messagingSenderId: '344217680049',
    projectId: 'collab-tasker',
    authDomain: 'collab-tasker.firebaseapp.com',
    storageBucket: 'collab-tasker.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLBx16V6By55l9napCr_0sIVdvWR19QzE',
    appId: '1:344217680049:android:77a9fcf3bf9c70dd3d0a90',
    messagingSenderId: '344217680049',
    projectId: 'collab-tasker',
    storageBucket: 'collab-tasker.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7K1NPdl0rPMFazL2CBAW73TFjHCQzUX4',
    appId: '1:344217680049:ios:946eb1e77d85e12c3d0a90',
    messagingSenderId: '344217680049',
    projectId: 'collab-tasker',
    storageBucket: 'collab-tasker.firebasestorage.app',
    iosBundleId: 'com.example.collabTasker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7K1NPdl0rPMFazL2CBAW73TFjHCQzUX4',
    appId: '1:344217680049:ios:946eb1e77d85e12c3d0a90',
    messagingSenderId: '344217680049',
    projectId: 'collab-tasker',
    storageBucket: 'collab-tasker.firebasestorage.app',
    iosBundleId: 'com.example.collabTasker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDGpbgq6Rt6qJO4rNfBKqxRKPQ-FmbX6RA',
    appId: '1:344217680049:web:af79a02afb1e10be3d0a90',
    messagingSenderId: '344217680049',
    projectId: 'collab-tasker',
    authDomain: 'collab-tasker.firebaseapp.com',
    storageBucket: 'collab-tasker.firebasestorage.app',
  );
}
